server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:8082'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: payment-service
          #         predicates =  payment-service로 요청이 들어오면
          predicates:
            - Path=/payment-service/**
          #         filter = 앞 1개 (/payment-service) 를 제거하고 payment-service로 요청을 보낸다
          filters:
            - StripPrefix=1
          #          아래 uri는 eureka에 등록된 서비스명, 각 서비스마다 spring.application.name으로 등록되어있음
          uri: lb://payment-service

        - id: member-service
          predicates:
            - Path=/member-service/**
          filters:
            - StripPrefix=1
          uri: lb://member-service

        - id: lecture-service
          predicates:
            - Path=/lecture-service/**
          filters:
            - StripPrefix=1
          uri: lb://lecture-service

        - id: lesson-service
          predicates:
            - Path=/lesson-service/**
          filters:
            - StripPrefix=1
          uri: lb://lesson-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/